add commas to coordinates in search command
DotEye/Minecraft-Library-of-Babel pull request #1
Opened 2022-10-03 06:01 UTC by n3s-online

Adding human readable strings for the search command.

When the coordinates for the search command get big (> 1,000,000, especially > 10,000,000) it becomes really hard to type out coordinates without any commas existing.

Technically it won't really do much for the Y coordinate but might as well apply it to that as well to be consistent.

2022-10-03 06:12 UTC, DotEye requested changes
Could we also change the coordinate parser to accept/ignore commas?

2022-10-03 06:12 UTC, DotEye commented on src/helper.js
> +}
No newline at end of file.

2022-10-03 06:43 UTC, n3s-online commented on src/helper.js
> +}
yes

2022-10-03 06:43 UTC, n3s-online commented
should be all fixed

2022-10-05 02:13 UTC, DotEye approved these changes

2022-10-05 02:14 UTC, merged

2022-10-05 02:20 UTC, DotEye commented
Your `.replace` call doesn't work for strings with more than one comma.

```js
> '1,000,000'.replace(new RegExp(','), '')
'1000,000'
```

2022-10-05 02:23 UTC, DotEye commented
Since this PR is already merged, I fixed the issue in this commit: https://github.com/DotEye/Minecraft-Library-of-Babel/commit/cc4fe316c86c4d9e60d2d7fb4eaa24590317f42e